# see also https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

# Disable submodules for the time being - they seem to not respect the branch of scripts we're using.
#  - package-ecosystem: "gitsubmodule"
#    directory: "/"
#    schedule:
#      interval: "daily"
      
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"
